version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: web
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: amocrm_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:


volumes:
  dbdata:
